# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=80)),
                ('fecha', models.DateField(max_length=10)),
                ('hora', models.TimeField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TareasPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizador.Actividad')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizador.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='actividades',
            field=models.ManyToManyField(through='organizador.TareasPersona', to='organizador.Actividad'),
        ),
    ]
